version: '3.9'

services:
  # TODO support nested tf dirs
  terraform:
    image: hashicorp/terraform:1.4.4
    container_name: terraform-project-template-terraform
    volumes:
      - ./:/app
    working_dir: /app
    env_file: .env

networks:
  default:
    name: terraform-project-template-localnet
    driver: bridge